### ISSUE TITLE
Why does third party browser follow ie not work?

### ISSUE THREAD

**Issue by StrangerShen** [verymuch/blog#35]
如标题。。菜狗第一次提问。。我也不知道咋问，问题就是为什么第三方浏览器跟随ie不生效？

**Comment by verymuch** [comment]
首先，很高兴收到你的提问。
其次，对于问题的描述我不太能理解。跟随IE指的是什么？具体是什么样的问题或者是表现？我有点无从下嘴😂

**Comment by StrangerShen** [comment]
&nbsp; &nbsp; 大佬，事情是这样的。
&nbsp; &nbsp; 我的电脑要么不能挂梯子，要么挂梯子，就算是五倍流量的节点，下载速度最高也只有500k/s，而且github甚至不能看图片。我前前后后换了四个梯子，quickq我朋友能用的账号都借给我测试了，结果在我电脑上还是不能用。次元加速派了工程师用了netch和V2rayN派了三次远程操控我的电脑，最后得出结论我要重装系统
。我寻思重置系统应该也差不多，把系统设置改回来就行了，而且我也只改过hosts文件，加了几个github什么什么的CSDN上查文章抄的。然后我昨晚重置了，结果还是不行。然后又去问次元加速的工程师，就是让我重装系统，或者github上问问题，他们让我问的问题就是“为什么第三方浏览器无法跟随ie代理”，我自己也不明白这是什么意思。
&nbsp; &nbsp; 大佬，可以加个QQ吗。。我身边没有会电脑的人。。因为之前自己乱改改怕了。。您可以帮我解决一下我的电脑不能挂梯子的问题吗。万分感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "verymuch/blog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 上午9:46
收件人:&nbsp;"verymuch/blog"<blog@noreply.github.com&gt;;
抄送:&nbsp;"stranger"<369197761@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [verymuch/blog] Why does third party browser follow ie not work? (#35)





 
首先，很高兴收到你的提问。
 其次，对于问题的描述我不太能理解。跟随IE指的是什么？具体是什么样的问题或者是表现？我有点无从下嘴😂

**Comment by verymuch** [comment]
抱歉，这方面我不太擅长。如果专门的工程师都搞不定的话，我也无能为力了。

**Comment by StrangerShen** [comment]
好的，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "verymuch/blog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 下午2:12
收件人:&nbsp;"verymuch/blog"<blog@noreply.github.com&gt;;
抄送:&nbsp;"stranger"<369197761@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [verymuch/blog] Why does third party browser follow ie not work? (#35)





 
抱歉，这方面我不太擅长。如果专门的工程师都搞不定的话，我也无能为力了。
